// udp_broadcaster
//
// Reproduces the order stream generated by CreateMarket() in matcher.cpp and
// pushes it out over UDP multicast, as if it were arriving from the network.
// The order/message structs are the ground truth from <matcher/matcher.h>; the
// on-wire byte layout (explicit little-endian, field-by-field) lives in the
// shared udp_wire.h so this works locally AND across machines of any endianness
// or ABI. We only re-implement the generation logic here because CreateMarket()
// itself is not exported from the header.

#include <udp_wire.h>

#include <arpa/inet.h>   // inet_pton
#include <netinet/in.h>  // sockaddr_in, IPPROTO_*
#include <sys/socket.h>  // socket, setsockopt, sendto
#include <unistd.h>      // close

#include <chrono>
#include <cstdlib>
#include <limits>
#include <list>
#include <print>
#include <random>
#include <thread>
#include <utility>
#include <vector>

using namespace matcher;

namespace
{
// 239.0.0.0/8 is the administratively scoped multicast range: local use only,
// never routed onto the public internet.
constexpr char kGroup[] = "239.255.0.1";
constexpr uint16_t kPort = 30001;

// Faithful copy of CreateMarket()'s generation: same seed, same distributions,
// same cancel-injection pass, so the stream is identical to what the matcher
// would have fed itself internally.
std::list<NewRequest> GenerateOrders(size_t count)
{
	std::mt19937 gen(75);
	std::list<NewRequest> orders;
	size_t msgId = 1;

	std::uniform_int_distribution<int64_t> distribLots(500, 20000);
	std::uniform_int_distribution<size_t> distribTicks(40, 60);
	std::uniform_int_distribution<int32_t> distribType(0, 3);

	for (size_t i = 0; i < count; ++i)
	{
		int8_t ordTypeNum = static_cast<int8_t>(distribType(gen));
		OrderType ordType = static_cast<OrderType>(ordTypeNum);

		int64_t sign = (ordTypeNum < 2) ? 1 : -1; // -1 if selling
		int64_t lots = distribLots(gen) * sign;

		size_t ticks = distribTicks(gen);
		size_t ordIsLimit = (ordType == OrderType::BuyLimit || ordType == OrderType::SellLimit);

		orders.emplace_back(NewOrderRequest{.msgId = msgId,
			.order = {.id = msgId++, .quantityLots = lots},
			.orderType = ordType,
			.instrumentId = Instrument::Time,
			.priceTicksLimit = ordIsLimit * ticks});
	}

	bool skip = false;
	std::uniform_int_distribution<int32_t> cancelDistrib(0, 1);
	for (auto itr = orders.begin(); itr != orders.end(); std::advance(itr, 1))
	{
		if (std::exchange(skip, false))
			continue;
		if (!static_cast<bool>(cancelDistrib(gen)))
			continue;
		skip = true; // can't cancel a cancellation, so skip the next one

		NewOrderRequest& orderMsg = std::get<NewOrderRequest>(*itr);
		orders.emplace(std::next(itr, 1),
			CancelOrderRequest{.msgId = msgId++, .toCancel = orderMsg.order.id, .instrumentId = orderMsg.instrumentId});
	}
	return orders;
}
} // namespace

int main(int argc, char** argv)
{
	size_t count = (argc > 1) ? std::strtoul(argv[1], nullptr, 10) : 50;

	// SOCK_DGRAM = UDP: connectionless, message-oriented, unreliable.
	int fd = ::socket(AF_INET, SOCK_DGRAM, 0);
	if (fd < 0)
	{
		std::perror("socket");
		return 1;
	}

	// IP_MULTICAST_TTL bounds router hops. 1 keeps it on the local subnet.
	unsigned char ttl = 1;
	::setsockopt(fd, IPPROTO_IP, IP_MULTICAST_TTL, &ttl, sizeof(ttl));

	sockaddr_in dst{};
	dst.sin_family = AF_INET;
	dst.sin_port = htons(kPort);                 // header field -> network byte order
	::inet_pton(AF_INET, kGroup, &dst.sin_addr); // dotted-quad -> in_addr

	std::println("broadcasting {} orders to {}:{}", count, kGroup, kPort);


	std::byte buf[std::numeric_limits<uint16_t>::max()];
	uint16_t seqnum = 0;
	auto stream = GenerateOrders(count);
	for (const NewRequest& req : stream)
	{
		size_t len = wire::encodeDatagram(buf, seqnum++, req);
		if (::sendto(fd, buf, len, 0, reinterpret_cast<sockaddr*>(&dst), sizeof(dst)) < 0)
		{
			std::perror("sendto");
			return 1;
		}
		std::this_thread::sleep_for(std::chrono::milliseconds(2)); // pacing for the demo
	}

	// Sentinel sent a few times: UDP can drop, and there is no retransmit.
	size_t endLen = wire::encodeSentinel(buf, seqnum);
	for (int i = 0; i < 3; ++i)
		::sendto(fd, buf, endLen, 0, reinterpret_cast<sockaddr*>(&dst), sizeof(dst));

	std::println("done: sent {} messages", stream.size());
	::close(fd);
	return 0;
}
