// Project configuration injected by Vite from project.json
const PROJECT_NAME = __PROJECT_NAME__;
const PROJECT_DISPLAY_NAME = __PROJECT_DISPLAY_NAME__;

// Set page title and heading from config
document.getElementById('page-title').textContent = `${PROJECT_DISPLAY_NAME} - WebAssembly`;
document.getElementById('app-title').textContent = PROJECT_DISPLAY_NAME;

const consoleEl = document.getElementById('console');
const statusIndicator = document.getElementById('status-indicator');
const loadBtn = document.getElementById('load-btn');
const clearBtn = document.getElementById('clear-btn');

let module = null;

function log(msg, type = '') {
  const now = new Date();
  const time = now.toTimeString().slice(0, 8);
  const line = document.createElement('div');
  line.className = 'console-line';
  line.innerHTML = `
    <span class="console-time">${time}</span>
    <span class="console-msg ${type}">${msg}</span>
  `;
  consoleEl.appendChild(line);
  consoleEl.scrollTop = consoleEl.scrollHeight;
}

function setStatus(status) {
  statusIndicator.className = `status-indicator ${status}`;
}

clearBtn.addEventListener('click', () => {
  consoleEl.innerHTML = '';
  log('Console cleared', 'info');
});

loadBtn.addEventListener('click', async () => {
  if (module) {
    log('Module already loaded', 'info');
    return;
  }

  consoleEl.innerHTML = '';
  log('Loading WebAssembly module...', 'info');
  setStatus('loading');
  loadBtn.disabled = true;

  try {
    // Dynamic import of the ES6 module generated by Emscripten
    // __WASM_MODULE_PATH__ is replaced by Vite with the static string "./order_engine.js"
    const wasmModule = await import(__WASM_MODULE_PATH__);

    log('Initializing module...', 'info');

    // Create module instance with custom print handlers
    module = await wasmModule.default({
      print: (text) => log(text),
      printErr: (text) => log(text, 'error'),
    });

    log('Module loaded successfully!', 'success');
    setStatus('ready');
    loadBtn.textContent = 'Module Loaded';

  } catch (err) {
    log(`Failed to load module: ${err.message}`, 'error');
    setStatus('error');
    loadBtn.disabled = false;
  }
});

